// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pokemon.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PokemonEntry) Reset() {
	*x = PokemonEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonEntry) ProtoMessage() {}

func (x *PokemonEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonEntry.ProtoReflect.Descriptor instead.
func (*PokemonEntry) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PokemonEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PokemonEntryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon []*PokemonEntry `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
}

func (x *PokemonEntryList) Reset() {
	*x = PokemonEntryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonEntryList) ProtoMessage() {}

func (x *PokemonEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonEntryList.ProtoReflect.Descriptor instead.
func (*PokemonEntryList) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *PokemonEntryList) GetPokemon() []*PokemonEntry {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type PokemonEntryMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon map[string]*PokemonEntryList `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PokemonEntryMap) Reset() {
	*x = PokemonEntryMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonEntryMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonEntryMap) ProtoMessage() {}

func (x *PokemonEntryMap) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonEntryMap.ProtoReflect.Descriptor instead.
func (*PokemonEntryMap) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *PokemonEntryMap) GetPokemon() map[string]*PokemonEntryList {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

var File_pokemon_proto protoreflect.FileDescriptor

var file_pokemon_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x36, 0x0a, 0x0c, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a,
	0x10, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x22,
	0xa3, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x4d, 0x61, 0x70, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4d, 0x61, 0x70, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x1a, 0x52, 0x0a, 0x0c, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pokemon_proto_rawDescOnce sync.Once
	file_pokemon_proto_rawDescData = file_pokemon_proto_rawDesc
)

func file_pokemon_proto_rawDescGZIP() []byte {
	file_pokemon_proto_rawDescOnce.Do(func() {
		file_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pokemon_proto_rawDescData)
	})
	return file_pokemon_proto_rawDescData
}

var file_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pokemon_proto_goTypes = []interface{}{
	(*PokemonEntry)(nil),     // 0: main.PokemonEntry
	(*PokemonEntryList)(nil), // 1: main.PokemonEntryList
	(*PokemonEntryMap)(nil),  // 2: main.PokemonEntryMap
	nil,                      // 3: main.PokemonEntryMap.PokemonEntry
}
var file_pokemon_proto_depIdxs = []int32{
	0, // 0: main.PokemonEntryList.pokemon:type_name -> main.PokemonEntry
	3, // 1: main.PokemonEntryMap.pokemon:type_name -> main.PokemonEntryMap.PokemonEntry
	1, // 2: main.PokemonEntryMap.PokemonEntry.value:type_name -> main.PokemonEntryList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pokemon_proto_init() }
func file_pokemon_proto_init() {
	if File_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonEntryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonEntryMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_proto_goTypes,
		DependencyIndexes: file_pokemon_proto_depIdxs,
		MessageInfos:      file_pokemon_proto_msgTypes,
	}.Build()
	File_pokemon_proto = out.File
	file_pokemon_proto_rawDesc = nil
	file_pokemon_proto_goTypes = nil
	file_pokemon_proto_depIdxs = nil
}
